artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/poojapbabar/datasets/raw/0773e2f340fdc1954a8c887c3de92f2f8ae7d4da/hypothyroid.zip
  #source_URL:  https://github.com/poojapbabar/datasets/blob/6535e6336cda5b4a845e55de9ee81ff4060e0289/wineQT.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion



data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts\data_ingestion\hypothyroid\thyroid_data.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts\data_ingestion\hypothyroid\thyroid_data.csv


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib
